variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "ap-northeast-2"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "project_name" {
  description = "Project name for resource naming"
  type        = string
  default     = "terraform-aws"
}

variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"

  validation {
    condition     = can(cidrhost(var.vpc_cidr, 0))
    error_message = "VPC CIDR must be a valid IPv4 CIDR block."
  }
}

variable "availability_zones" {
  description = "Availability zones"
  type        = list(string)
  default     = ["ap-northeast-2a", "ap-northeast-2b"]

  validation {
    condition     = length(var.availability_zones) >= 2
    error_message = "At least 2 availability zones must be specified for RDS subnet group."
  }
}

variable "public_subnet_cidr" {
  description = "CIDR block for public subnet (EC2)"
  type        = string
  default     = "10.0.1.0/24"
}

variable "private_subnet_rds_cidr" {
  description = "CIDR block for private subnet (RDS)"
  type        = string
  default     = "10.0.2.0/24"
}

variable "private_subnet_rds_cidr_2" {
  description = "CIDR block for second private subnet (RDS) - required for DB subnet group"
  type        = string
  default     = "10.0.3.0/24"
}

variable "private_subnet_nlb_cidr" {
  description = "CIDR block for private subnet (NLB)"
  type        = string
  default     = "10.0.4.0/24"
}

variable "rds_admin_username" {
  description = "RDS admin username"
  type        = string
  default     = "admin"
}

variable "rds_admin_password" {
  description = "RDS admin password"
  type        = string
  default     = "test1234"
  sensitive   = true

  validation {
    condition     = length(var.rds_admin_password) >= 8
    error_message = "RDS admin password must be at least 8 characters long."
  }
}

variable "rds_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t3.micro"
}

variable "rds_allocated_storage" {
  description = "RDS allocated storage in GB"
  type        = number
  default     = 20

  validation {
    condition     = var.rds_allocated_storage >= 20 && var.rds_allocated_storage <= 1000
    error_message = "RDS allocated storage must be between 20 and 1000 GB."
  }
}

variable "ec2_instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.micro"
}

# EC2 Key Pair is now automatically generated by Terraform
# See keypair.tf for key pair generation

# Common Tags Configuration
variable "user_name" {
  description = "User name for Owner tag (e.g., john.doe)"
  type        = string
  
  validation {
    condition     = can(regex("^[a-zA-Z0-9._-]+$", var.user_name))
    error_message = "User name must contain only alphanumeric characters, dots, underscores, and hyphens."
  }
}

variable "remove_after" {
  description = "Date when resources can be removed (YYYY-MM-DD format)"
  type        = string
  default     = "2025-12-31"
  
  validation {
    condition     = can(regex("^[0-9]{4}-[0-9]{2}-[0-9]{2}$", var.remove_after))
    error_message = "Remove after date must be in YYYY-MM-DD format."
  }
}

variable "company_domain" {
  description = "Company domain for email addresses (e.g., company.com)"
  type        = string
  default     = "databricks.com"
}

variable "ec2_ssh_allowed_cidrs" {
  description = "CIDR blocks allowed for SSH access to EC2"
  type        = list(string)
  default     = ["0.0.0.0/0"]

  validation {
    condition     = length(var.ec2_ssh_allowed_cidrs) > 0
    error_message = "At least one CIDR block must be specified for SSH access."
  }
}

variable "ec2_web_allowed_cidrs" {
  description = "CIDR blocks allowed for HTTP/HTTPS access to EC2"
  type        = list(string)
  default     = ["0.0.0.0/0"]

  validation {
    condition     = length(var.ec2_web_allowed_cidrs) > 0
    error_message = "At least one CIDR block must be specified for web access."
  }
}

variable "enable_mysql_proxy" {
  description = "Enable MySQL proxy on EC2 instance (forwards port 3306 to RDS)"
  type        = bool
  default     = false
}

variable "mysql_proxy_allowed_cidrs" {
  description = "CIDR blocks allowed for MySQL proxy access (only used if enable_mysql_proxy is true)"
  type        = list(string)
  default     = ["10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12"]

  validation {
    condition = length(var.mysql_proxy_allowed_cidrs) > 0
    error_message = "At least one CIDR block must be specified for MySQL proxy access."
  }
}

variable "enable_nlb" {
  description = "Enable Network Load Balancer for MySQL proxy (only works if enable_mysql_proxy is also true)"
  type        = bool
  default     = false
}

variable "nlb_allowed_cidrs" {
  description = "CIDR blocks allowed for NLB MySQL access (only used if enable_nlb is true)"
  type        = list(string)
  default     = ["10.0.0.0/16"]  # Default to VPC CIDR

  validation {
    condition = length(var.nlb_allowed_cidrs) > 0
    error_message = "At least one CIDR block must be specified for NLB access."
  }
}

# VPC Endpoint Service Configuration (PrivateLink)
variable "enable_endpoint_service" {
  description = "Enable VPC Endpoint Service for PrivateLink access to NLB"
  type        = bool
  default     = false
}

variable "endpoint_service_allowed_principal" {
  description = "AWS principal ARN allowed to access the endpoint service"
  type        = string
  default     = ""
  
  validation {
    condition = var.endpoint_service_allowed_principal == "" || can(regex("^arn:aws:iam::", var.endpoint_service_allowed_principal))
    error_message = "Principal must be a valid AWS IAM ARN starting with 'arn:aws:iam::' or empty string."
  }
}

variable "assign_public_ip_to_ec2" {
  description = "EC2 subnet placement: true = public subnet + public IP, false = private subnet + no public IP"
  type        = bool
  default     = true  # Default to public subnet for easier testing and development
}

variable "enable_nat_gateway" {
  description = "Enable NAT Gateway for internet access from private subnet (needed for yum install, updates, etc.)"
  type        = bool
  default     = false
}

# Databricks Configuration
variable "enable_databricks_ncc" {
  description = "Enable Databricks Network Connectivity Configuration (NCC) for PrivateLink integration"
  type        = bool
  default     = false
}

variable "databricks_account_id" {
  description = "Databricks Account ID for NCC configuration"
  type        = string
  default     = ""
  
  validation {
    condition = var.databricks_account_id == "" || can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", var.databricks_account_id))
    error_message = "Databricks Account ID must be a valid UUID format (e.g., 12345678-1234-1234-1234-123456789abc) or empty string."
  }
}

variable "databricks_client_id" {
  description = "Databricks OAuth Client ID for authentication"
  type        = string
  default     = ""
  sensitive   = true
}

variable "databricks_client_secret" {
  description = "Databricks OAuth Client Secret for authentication"
  type        = string
  default     = ""
  sensitive   = true
}

